// Scraped from https://www.scarymommy.com/interesting-facts/

export const facts = [
    "Polar bear fur is actually clear, and their skin is black.",
    "Baby flamingos are born grey, not pink.",
    "A woodpecker’s tongue actually wraps all the way around its brain, protecting it from damage when it’s hammering into a tree.",
    "A shrimp’s heart is located in its head.",
    "Elephants suck on their trunks for comfort.",
    "Anteaters have no teeth.",
    "Nine-banded armadillos always have quadruplets, and they’re always identical.",
    "Wombat poop is cube-shaped.",
    "Hippos and horses are actually distant relatives.",
    "All clownfish are born male.",
    "In the UK, The Queen legally owns all unmarked swans.",
    "To keep from drifting apart, sea otters hold hands while they sleep.",
    "Goats have accents.",
    "Dolphins give names to each other.",
    "Gorillas can catch human colds — you’re probably still safe to go to the zoo with the sniffles, though.",
    "Forget bald eagles. The turkey was once almost named the national bird.",
    "A group of owls is called a parliament.",
    "There are 32 muscles in a cat’s ear.",
    "Snails can regenerate their eyes.",
    "Want to know if your pet turtle is a boy or girl? Listen closely! Female turtles hiss and male turtles grunt.",
    "A starfish can turn its stomach inside out.",
    "French Poodles are actually from Germany.",
    "Seahorses mate for life and can often be seen holding each other’s tales.",
    "A group of porcupines is called a prickle.",
    "Andrew Jackson’s parrot had to be removed from his funeral because it wouldn’t stop swearing. Polly wants her mouth washed out.",
    "Sloths can hold their breath for up to 40 minutes.",
    "Henry VIII knighted all four of his \"Grooms of Stool\" — the people in charge of wiping his butt for him.",
    "Jeannette Rankin was elected to Congress four years before women could even vote.",
    "Women couldn’t apply for credit at a bank until 1974.",
    "Before the invention of modern false teeth, dentures were commonly made from the teeth of dead soldiers.",
    "In ancient Egypt, servants were smeared with honey so flies would flock to them instead of the pharaoh.",
    "It was once considered sacrilegious to use a fork.",
    "Abe Lincoln was a champion wrestler. He was also a licensed bartender. Maybe they should call him an \"Abe of all trades.\"",
    "George Washington owned a whiskey distillery.",
    "More than two percent of the American population was killed during the Civil War.",
    "Joseph Stalin used to have people removed from photos after they died or were removed from office.",
    "Since 1945, all British tanks have been equipped with the necessary items for making tea.",
    "Pope Gregory IV once declared war on cats because he believed Satan used black cats. His declaration lead to the mass extermination of cats, causing a rat infestation which led to the spread of the plague.",
    "John Adams was the first president to live in the White House.",
    "Go to bed! Chernobyl, the Exxon Valdez Oil Spill, and the Challenger explosion have all been attributed to a lack of sleep.",
    "The average person living in Sweden eats about 22 pounds of chocolate a year.",
    "While the Wright Brothers are famous as a pair, they actually only flew together once. They promised their father they’d always fly separately.",
    "Montana has three times as many cows as it does people.",
    "Parts of the Great Wall of China were made with sticky rice.",
    "Ninety percent of the world’s population lives above the equator.",
    "Finland has more saunas than cars.",
    "Sixty percent of the World’s lakes (three million in total) are located in Canada.",
    "Virginia is the only state that has the same state flower and state tree, the Dogwood.",
    "Think before you season. In Egypt, it’s considered incredibly rude to salt food that has been served to you.",
    "Ninety percent of Libya is desert.",
    "The height of the Eiffel Tower can vary up to six inches, depending on the temperature.",
    "Spend too much on drinks when you eat out? A small town in Italy actually has a fountain that serves free wine.",
    "Pilots and their co-pilots are required to eat different meals before flights so that they don’t both end up with food poisoning.",
    "Want to go to Rome? Which one? There’s a city named Rome on six out of seven continents. (You really dropped the ball, Antarctica.)",
    "When visiting Key West, you’re actually closer to Havana than you are to Miami.",
    "Mary, of \"Mary Had A Little Lamb\" fame, was a real person and the song is based on a true story.",
    "\"Happy Birthday\" was the first song ever played on Mars. Mars Rover Curiosity played the song to itself on its first anniversary on the planet.",
    "While listening to music, your heart can sync to the rhythm.",
    "President Nixon was an accomplished musician. He played five instruments, including the accordion.",
    "Got a song stuck in your head? That’s called an \"earworm.\"",
    "None of The Beatles could actually read music. However, George Harrison could reportedly play 26 instruments.",
    "Barry Manilow did not, in fact, write \"I Write The Songs.\"",
    "Metallica is the only band to perform on all seven continents.",
    "Most department stores tend to play slower music, in order to slow down customers and keep them shopping longer. The opposite is true for restaurants.",
    "Monaco’s orchestra is bigger than its army.",
    "A concert promoter once sold a thousand tickets to a Spice Girls concert in Hawaii that was never actually booked. Maybe that’s where they got the idea for Fyre Fest.",
    "Leo Fender, the inventor of the Stratocaster and the Telecaster, couldn’t play guitar.",
    "In 2016, Mozart sold more albums than Beyoncé.",
    "During a fundraiser for Hurricane Katrina relief efforts, someone donated $35,000 so that VH1 Classic would have to play \"99 Luftballons\" on repeat for an entire hour.",
    "In 2015, Belfast police used ice cream truck music to deter teenage rioters.",
    "Gatorade was named after the University of Florida Gators.",
    "China didn’t win its first Olympic medal until 1984.",
    "The average golf ball has 336 dimples.",
    "Tennis was originally played with bare hands.",
    "The Cleveland Browns are the only team to neither play in or host a Super Bowl.",
    "Some golf balls are filled with honey.",
    "Despite taking about three hours to play out, the average baseball game only has about 18 minutes of active playing time.",
    "MLB umpires are required to wear black underwear in case they split their pants.",
    "Bo Jackson refused the teams that originally tried to draft him in both baseball and football.",
    "Both volleyball and basketball were invented in Massachusetts.",
    "Michael Jordan and the Chicago Bulls once went eight seasons (starting in 1990) without a three-game losing streak.",
    "NFL refs also get Super Bowl rings.",
    "President Hubert Hoover invented a game called \"Hooverball\" which was a cross between tennis and volleyball and was played with a medicine ball.",
    "Only one city has won three major championships in one year. In 1935, the Detroit Lions won the Super Bowl, the Tigers won the world series, and the Red Wings won the Stanley Cup.",
    "More than 100 baseballs are used during a typical professional baseball game.",
    "You can’t hum while plugging your nose.",
    "Tomatoes have more genes than humans.",
    "We’re one to two centimeters taller in the morning than at night.",
    "One quarter of all our bones are in our feet.",
    "The human body contains enough fat to make about seven bars of soap.",
    "You can’t lick your elbow.",
    "You can’t tickle yourself.",
    "By the time we die, we’ll have spent roughly a year sitting on the toilet.",
    "You are always looking at your nose; your brain just chooses to ignore it.",
    "Astronauts can grow up to two inches taller while they’re in space.",
    "Some blood vessels in a blue whale are actually big enough for humans to swim through.",
    "We’re the only species known to blush.",
    "You only breathe out of one nostril at a time.",
    "Babies are born with more bones than adults. (Babies have 300 bones while adults only have 206.)",
    "Most newborns lose all the hair they were born with by the time they’re six months old.",
    "It’s impossible to burp in space.",
    "Everyone has their own unique smell, except identical twins.",
    "Thumbs have their own pulse.",
    "Goosebumps developed to make our ancestors’ hair stand up, making them appear more threatening to predators.",
    "A sneeze shoots through the air at 100 miles per hour, sending 10,000 germs flying.",
    "Humans are capable of echolocation, just like bats or whales.",
    "Stomach acid is strong enough to dissolve metal.",
    "The longest hiccuping spell lasted a whopping 68 years.",
    "Guide dogs do their \"business\" on command — to make things easier for their owners. So considerate!",
    "In WWII British soldiers had to make do with only three sheets of toilet paper per day!",
    "In Russia, beer was considered a soft drink, not alcohol, until 2011!",
    "Strawberries are actually NOT berries, but bananas are!",
    "The cashew nuts we eat are actually attached to a large cashew apple that is used to make soft drinks in Brazil. Ca-shew on that fact!",
    "Mice actually do not like cheese! They prefer sweets if given the choice — they like to eat fruit, seeds, and grains!",
    "Turkey was probably not eaten at the first Thanksgiving — instead, wildfowl, goose, and even possibly passenger pigeons and swans were consumed!",
    "A flock of ravens is called a conspiracy. Dark stuff!",
    "Caterpillars have 12, count ‘em, 12 eyes!",
    "Mice have pretty funny names: A female mouse is a doe and a male mouse is a buck. Baby mice are sometimes called pinkies because of their color and sometimes called pups.",
    "Did you know that gorillas, monkeys, bonobos, and other primates make a new nest to sleep in every night?!",
    "Chickens don’t just eat seeds, they like to eat insects and also mice and lizards! Ew, chickens!",
    "Giraffes don’t just have long necks - they have long tongues! Their tongues are between 18 and 20 inches long.",
    "In Arizona, you can’t feed garbage to pigs without getting a permit.",
    "Sea otters like to hold each other’s paws when they sleep, so they don’t drift apart while dreaming. How sweet is that?!",
    "Did you know that jellyfish have been around even before dinosaurs?",
    "All clownfish are born male! They can also all change their sex to female, but they can’t turn it back to male after doing so. So Nemo could become a girl fish all along!",
    "Did you know apples come from the same plant family as roses? So do plums, raspberries, and many other delicious fruits. Next time, instead of roses, just send your mother a lovely bouquet of plums!",
    "The first Akita dog came to this country in 1937 — as a present for Helen Keller!",
    "Turns out, a dog’s paw print is just as unique as a human’s. Good news for dog detectives!",
    "A camel can drink up to 40 gallons of water in one go. That’s seriously impressive!",
    "Don’t bring your crystal ball to Maryland! Fortune telling is illegal in the state.",
    "Speaking of ferrets, did you know they used to be used to protect grain stores from rodents?",
    "The technical term for a fear of long words is \"hippopotomonstrosesquippedaliophobia.\" No way you can self-diagnose yourself with that one!",
    "The White House has 35 bathrooms.",
    "Greyhounds can run up to 45mph, so don’t challenge one to a race!",
    "Hiking naked is illegal in Switzerland. Though we must say, it doesn’t seem like a good idea in general!",
    "A flock of flamingos is called… wait for it… a flamboyance! Fancy.",
    "New York’s Central Park is bigger than Monaco.",
    "Using ferrets to hunt other animals is illegal in West Virginia. Good to know!",
    "Don’t let the chicken cross the road in Georgia (the country.) No, seriously. It’s illegal!",
    "Here’s a fact to sit on: there are over 9,000 benches in Central Park.",
    "Theodore Roosevelt’s kids had a pet bear, badger, and hyena, to name but a few animals — and they brought them all to the White House!",
    "There are over 700 ancient Egyptian hieroglyphic symbols. That’s a lot compared to 26 letters of the alphabet!",
    "A woodpecker’s tongue is bigger than its entire head. It keeps it wrapped up around its brain to protect it from the impact of all that pecking!",
    "Saturn’s surface is less dense than water. That means it could float in your bathtub — if it were big enough.",
    "The expression \"heart of gold\" was invented by Shakespeare.",
    "To make one pound of honey, a bee has to fly 90,000 miles! Though one bee typically only makes one-twelfth of a teaspoon of the stuff in its lifetime.",
    "Some lipsticks apparently contain fish scales. Eek!",
    "An ostrich’s eye is actually bigger than its brain. Ostriches also have the largest eye of any land animal.",
    "The United States apparently makes 25 percent of the world’s cheese. That’s a whole lot of cheese!",
    "The human hand has 54 bones. That’s more than a quarter of the bones in the whole body. Wow!",
    "Want a license plate in the shape of a polar bear? All you have to do is move to Nunavut Province in Canada!",
    "How do you tell if a cranberry is ripe? It’ll bounce like a rubber ball.",
    "Most U.S. stamp adhesive contains about one-tenth of a calorie. British stamps could set you back 5.9 calories. Of course, one lick won’t transfer all of that to your belly.",
    "Here’s a little funny and creepy fact: not only are groups of crows called murders, but the birds actually hold funerals for their dead. Spooky!",
    "Bees are the only insect that produce food that people eat. Thanks, bees!",
    "Squeamish? Don’t go to any cheese shops in Sardinia, lest you find yourself face to face with Casu Marzu, a cheese that gets its taste from live maggots. Eek!",
    "Lettuce is a member of the sunflower family.",
    "Jin Songhao of China won the world record for longest skin contact with snow at 46 minutes and 7 seconds!",
    "The heaviest onion on record was grown by Pete Glazebrook of England. It weighed 17 pounds!",
    "The title of tallest Mohawk goes to Kazuhito Watanabe, a Japanese fashion designer. His ‘hawk’ measures three feet 8.6 inches!",
    "Elmer Fudd’s original name was Egghead.",
    "The actors who voiced Mickey and Minnie mouse from the 1980s to the 2010s were married!",
    "In some Harry Potter movie scenes where Harry, Ron, and Hermione are doing their Hogwarts schoolwork, the actors were actually doing their REAL schoolwork!",
    "The oldest domestic cat on record lived for 38 years. She was Creme Puff of Austin, Texas.",
    "Apparently, the world’s fastest ant runs faster than Usain Bolt!",
    "Little brown bats make for the longest nappers — in captivity, they nap up to 19.9 hours a day. Wish we could take a nap that long!",
    "The longest noodle ever made is more than 10,000 feet long. That’s almost two miles! Wonder how long it would take us to slurp that?",
    "Otto the bulldog broke the record for a dog to skate through the longest human tunnel when he skated through the legs of 30 people without any assistance. Otto, you’re our hero.",
    "A flock of peacocks is called a party. Party hard, peacocks!",
    "The Supreme Court has its own basketball court, with a great nickname: \"The highest court on the land!\" Get it?!",
    "Time stops at the speed of light.",
    "The average human body carries more bacteria cells than human cells.",
    "In their lifetime, the average person walks the equivalent of five times around the Earth.",
    "Humans wouldn’t be able to taste food without saliva.",
    "If Betelgeuse exploded right now, the star’s last light show would brighten our sky for around two months.",
    "Oona Chaplin, who played Robb Stark’s wife in Game of Thrones, is Charlie Chaplin’s granddaughter.",
    "The founder of sportswear companies Puma and Adidas were brothers! Rudolf \"Rudi\" Dassler is the brain behind Puma, while his big bro Adolf \"Adi\" Dassler gave the world Adidas.",
    "The only letter of the alphabet that doesn’t appear in any American state is \"q.\"",
    "The original Ferris Wheel was designed and constructed in Chicago, Illinois, by George Washington Gale Ferris, Jr.",
    "While SPAM is most popular in Hawaii, it was actually invented in Minnesota. The state even serves as home to the SPAM museum!",
    "Glaciers, ice caps, and ice sheets hold nearly 69 percent of the world’s freshwater.",
    "Whale songs can be used by scientists to sonically map out the ocean floor.",
    "The first person charged with speeding in a vehicle was going eight miles per hour.",
    "Hair and nails typically grow faster during pregnancy.",
    "Cardinals cover themselves in ants to get rid of lice and other harmful parasites that might be in their feathers."
]